### ISSUE TITLE
Customize the top panel

### ISSUE THREAD

**Issue by young666** [pop-os/docs#38]
As the title, could I customize the top panel, thanks in advance :D

**Comment by dragonbite** [comment]
Have you tried any of the Gnome Shell Extensions? 
[https://extensions.gnome.org/](https://extensions.gnome.org/)
I think there are some panel customizing extensions available (make it transparent, etc.) 

Unfortunately since Gnome have moved to Gnome 3 / Gnome shell the ability to right-click and customize elements of the desktop, like the panel, has been tossed to the wayside.  It's slowly getting better but nothing like it used to be.

**Comment by ahoneybun** [comment]
I think this goes over that pretty well:

https://support.system76.com/articles/customize-gnome/
